### ISSUE TITLE
GitHub question - multiple remotes?

### ISSUE THREAD

**Issue by lopierra** [pdxrlang/tidy_tuesday_share#1]
Thanks for setting up this repo! 

So I have my R project for the Office data in a local repository, with a repo on my personal GitHub as remote (https://github.com/lopierra/tt_meetup). Is there some way I can add this pdxrlang repo as a second remote so I can push my files there too? Or do I just have to fork this repo and copy/paste my files into a new project folder? That doesn't seem right.

Hope this question makes sense - I am still pretty fuzzy on anything beyond the super-basics of git. Thanks!

**Comment by knausb** [comment]
Hi @lopierra , I'm a participant here but not an organizer. So they may have different advice than I do. But my general knowlege of the Git/GitHub workflow is that you fork the repo, create a branch, make your changes on your branch, update your repo, and then make a pull request with the original repo. Good luck!

**Comment by laderast** [comment]
I haven't set this up before, but here is a gist that talks about multiple remotes: https://gist.github.com/rvl/c3f156e117e22a25f242

My solution tends to be to clone the other repo, and use rsync to keep the two repo folders synced up.

**Comment by lopierra** [comment]
Thanks Brian and Ted. I realized that the multiple remotes thing might not work because I don't have push access to this repo. I will try it and see what happens, and will look into rsync.
